#!/usr/bin/env bash
# a bash script that configures a domain zone;

func(){
	r="$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | grep 'IN' | awk '{print $4}')"
	dest="$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | grep 'IN' | awk '{print $5}')"
	echo "The subdomain $2 is a $r and points to $dest"
}

if (( $# == 1 ));
   then
	func "$1" "www"
	func "$1" "lb-01"
	func "$1" "web-01"
	func "$1" "web-02"

else
	func "$1" "$2"
fi
