#!/usr/bin/env/bash
# a bash script that configures web-02 to be identical to web-01:

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
file="/etc/nginx/sites-available/default"
sed -i '/^\tserver/add_header X-Served-By \"\$HOSTNAME\"/\\n\t\}\n' $file
sudo service nginx restart
