#!/usr/bin/env bash
# add header to Nginx configuration file.
apt-get update
apt-get install -y nginx
file="/etc/nginx/sites-available/default"
echo -e "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sed -i 's/#error_page 404/error_page 404/' $file
echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
sed -i '/^\tserver_name localhost;/a\\n\tlocation \/redirect_me \{\n\t\treturn 301 https://www.youtube.com/watch?v=ZxD3o-9H1lY;\n\t\}\n\tadd_header X-Served-By "$HOSTNAME";' $file
sudo service nginx restart
