#!/usr/bin/env bash
# a script that install a load balancer

sudo apt-get install haproxy
file="/etc/default/haproxy"
sudo sed 's/ENABLED=0/ENABLE=1/' file
file_2="/etc/haproxy/haproxy.cfg"
echo "backend nodes
	balance roundrobin
	server 373-web-01 35.190.162.122:80 check
    	server 373-web-02 35.237.116.99:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

