#!/usr/bin/env bash
# a Bash script that generates a MySQL dump and creates a compressed archive;

mysqldump -u root -p"$1" --all-databases > backup.sql
name=$(date '+%d-%m-%Y')
tar -zcvf "$name.tar.gz" backup.sql
