#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument; should ping the IP 5 times.
if [ $# -ne 1 ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping "$1" -c 5
fi
