#!/usr/bin/env bash
# This script displays numbers from 1 to 100.

n=0;

while ((n++ <100));
do
if ((n % 3 == 0 && n % 5 == 0))
   then
	echo "FizzBuzz"
   elif ((n % 3 == 0))
   then
	echo "Fizz"
   elif ((n % 5 == 0))
   then
	echo "Buzz"
   else
	echo "$n"
fi
done