#!/usr/bin/env bash
# a Bash script that displays Holberton School 10 times
# but for the 9th iteration, displays Holberton School and then Hi on \n

n=0;
while ((n++ < 10));
do
if ((n == 9))
   then
	echo "Hi"
   else
	echo "Holberton School"
fi
done
