#!/usr/bin/env bash
# a bash script that configures a new ubuntu machine:

sudo apt-get update
sudo apt-get -y install nginx
ssh ubuntu@35.237.160.254 -p 80
"echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html"
