#!/usr/bin/env bash
# a bash script that configures the Nginx server to redirect to another page.

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html"
sudo service nginx start
file=/etc/nginx/sites-available/default
new_string="\s\n\t location /redirect_me {\n\t return 301 https://giphy.com/explore/this-is-bullshit}\n"
sed -i "s/^server$/$new_string/" $file
sudo service nginx restart
