#!/usr/bin/env bash
# a bash script to configure a custom 404 error page on Nginx:

apt-get update
apt-get -y install nginx
file=/etc/nginx/sites-available/default
echo -e "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i 's|#error_page 404 /404.html;|error_page 404 /404.html;|' $file
service nginx restart
