#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
sed -i 's/^127.*$/127.0.02 localhost/' /etc/hosts
sed -i "$ a 8.8.8.8 gacebook.com" /etc/hosts
